[package]
name = "Searchtextcli"
version = "0.1.0"
authors = ["David Alfonso davidalfonsook@gmail.com"]
license = "MIT OR Apache-2.0"
description = "A grep clone"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.32", features = ["derive"] }
indicatif = "0.17.11"
